server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # folder pe disc, editabil live (fara classpath ca sa nu suprascrie valorile editate)
          search-locations: file:./config-repo,file:./config-server/config-repo

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
